### ISSUE TITLE
Val error

### ISSUE THREAD

**Issue by cpy0029** [zifuwan/Sigma#11]
I apologize for the inconvenience, but I seem to have encountered another issue. 

After training for 50 epochs on the NYU dataset, during the val phase, it prompts 'CUDA out of memory'.

I am using a single A6000 48GB, and the batch size during training is set to 2. All other variables adhere to the original code.

**Comment by zifuwan** [comment]
Hi, glad to help with your issues.
- First, I recommend modifying the config files to: `C.num_train_imgs = {a smaller number, e.g., 10}`, `C.checkpoint_start_epoch = 0`,  and `C.checkpoint_step = 1`. In this way, you can quickly go to the evaluation phase without training for a long time. After all issues are settled, you can modify back the config.
- Second, could you monitor the GPU usage during evaluation and see which card is out of memory?
- Third, are you using single or distributed training?

**Comment by zifuwan** [comment]
Hi, glad to help with your issues.
- First, I recommend modifying the config files to: `C.num_train_imgs = {a smaller number, e.g., 10}`, `C.checkpoint_start_epoch = 0`,  and `C.checkpoint_step = 1`. In this way, you can quickly go to the evaluation phase without training for a long time. After all issues are settled, you can modify back the config.
- Second, I hardcoded the device numbers in [https://github.com/zifuwan/Sigma/blob/main/train.py#L255](https://github.com/zifuwan/Sigma/blob/main/train.py#L255). Could you try to modify the device number to [0]?

**Comment by cpy0029** [comment]
Thank you very much for your reply. I set C.num_train_imgs = 4, and after changing train.py#L255 to device = [0], the following error occurred during validation:

>   File "/home/code/Sigma/eval.py", line 27, in func_per_iteration
>     pred = self.sliding_eval_rgbX(img, modal_x, config.eval_crop_size, config.eval_stride_rate, device)
>                                                 ^^^^^^^^^^^^^^^^^^^^^
> AttributeError: 'NoneType' object has no attribute 'eval_crop_size'

However, in the config, C.eval_crop_size = [480, 640].

**Comment by cpy0029** [comment]
> Thank you very much for your reply. I set C.num_train_imgs = 4, and after changing train.py#L255 to device = [0], the following error occurred during validation:
> 
> > File "/home/code/Sigma/eval.py", line 27, in func_per_iteration
> > pred = self.sliding_eval_rgbX(img, modal_x, config.eval_crop_size, config.eval_stride_rate, device)
> > ^^^^^^^^^^^^^^^^^^^^^
> > AttributeError: 'NoneType' object has no attribute 'eval_crop_size'
> 
> However, in the config, C.eval_crop_size = [480, 640].

After debugging, I found that config = {NoneType} None.

**Comment by zifuwan** [comment]
Hi, sorry for the bug. Could you add config in `train.py` like this: [https://github.com/zifuwan/Sigma/commit/b490036ae41105ab9f57e1554607cd3c422e698a#diff-ed183d67207df065a11e1289f19d34cc2abbc5448dea952683cfe9728c342b95R256](https://github.com/zifuwan/Sigma/commit/b490036ae41105ab9f57e1554607cd3c422e698a#diff-ed183d67207df065a11e1289f19d34cc2abbc5448dea952683cfe9728c342b95R256). Besides, please set device=[0] as I mentioned before.
Sorry for the inconvenience.
Best.

**Comment by cpy0029** [comment]
Thank you for your prompt response. I have already been able to enter the val stage.

But after I have val 654 images, the following problem will occur again, which should still be due to a missing definition in some configuration.

> 27 19:33:27 begin trainning:
> Epoch 1/500 Iter 2/2: lr=3.0000e-06 loss=5.6572 total_loss=5.3168: [00:07<00:00, 3.80s/it]
> 27 19:33:35 Saving checkpoint to file /home/code/Sigma/log_final/log_nyudepth/log_NYUDepthv2_sigma_tiny_cromb_conmb_cvssdecoder/checkpoint/epoch-1.pth
> 27 19:33:36 Save checkpoint to file /home/code/Sigma/log_final/log_nyudepth/log_NYUDepthv2_sigma_tiny_cromb_conmb_cvssdecoder/checkpoint/epoch-1.pth, Time usage:
> 	prepare checkpoint: 0.008490562438964844, IO: 1.8830058574676514
> 27 19:33:37 Load Model: /homecode/Sigma/log_final/log_nyudepth/log_NYUDepthv2_sigma_tiny_cromb_conmb_cvssdecoder/checkpoint/epoch-1.pth
> 27 19:33:37 GPU 0 handle 654 data.
> 100%|███████████████████████████████████████| 654/654 [1:55:13<00:00, 10.57s/it]
> 27 21:28:50 WRN A exception occurred during Engine initialization, give up running process
> Traceback (most recent call last):
>   File "/home/chen/code/Sigma/train.py", line 262, in <module>
>     _, mean_IoU = segmentor.run(config.checkpoint_dir, str(epoch), config.val_log_file,
>                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/code/Sigma/engine/evaluator.py", line 90, in run
>     result_line, mean_IoU = self.single_process_evalutation()
>                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/code/Sigma/engine/evaluator.py", line 237, in single_process_evalutation
>     result_line, mean_IoU = self.compute_metric(all_results)
>                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/code/Sigma/eval.py", line 63, in compute_metric
>     hist = np.zeros((config.num_classes, config.num_classes))
>                      ^^^^^^
> NameError: name 'config' is not defined

**Comment by zifuwan** [comment]
Hi, sorry for the bug. I've updated the code, and if you specify [0] GPU for evaluation, you'll be all good.
