### ISSUE TITLE
Excuse me, I still encounter the problem of 'no config' after the val complete.

### ISSUE THREAD

**Issue by cpy0029** [zifuwan/Sigma#12]
Excuse me, I still encounter the problem of 'no config' after the verification is complete.

> Traceback (most recent call last):
>   File "/home/code/Sigma/train.py", line 265, in <module>
>     _, mean_IoU = segmentor.run(config.checkpoint_dir, str(epoch), config.val_log_file,
>                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/code/Sigma/engine/evaluator.py", line 90, in run
>     result_line, mean_IoU = self.single_process_evalutation()
>                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/code/Sigma/engine/evaluator.py", line 237, in single_process_evalutation
>     result_line, mean_IoU = self.compute_metric(all_results)
>                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> TypeError: SegEvaluator.compute_metric() missing 1 required positional argument: 'config'

**Comment by zifuwan** [comment]
Hi, could you pull the newest commit? It may need to modify like this: https://github.com/zifuwan/Sigma/commit/c494c0f1207591d0e4db7e861a9cbf7290da526e#diff-171b46a295bd22464bf6f2296dda72e6f5b8ed754d98d05f25add040803f3801R237

**Comment by zifuwan** [comment]
Hi, if the question is resolved, I'm closing this issue now.
