### ISSUE TITLE
fusion module

### ISSUE THREAD

**Issue by kkkkkkkb** [zifuwan/Sigma#13]
请问fusion module可以即插即用吗～ 
我试了一下效果变差了，不知道是哪里出了问题，我融合的是两种医学MRI图像Flair和T1。
融合之前我也对两个特征进行了contiguous和FRM处理。

**Comment by zifuwan** [comment]
抱歉没有在这些任务上做过实验。从理论上是会更好的。但可以尝试只使用CroMB或ConMB，或许对特定任务更好些。

**Comment by kkkkkkkb** [comment]
> 抱歉没有在这些任务上做过实验。从理论上是会更好的。但可以尝试只使用CroMB或ConMB，或许对特定任务更好些。

好的收到，谢谢回复！我再试一下只使用CroMB或ConMB～

**Comment by kkkkkkkb** [comment]
> 抱歉没有在这些任务上做过实验。从理论上是会更好的。但可以尝试只使用CroMB或ConMB，或许对特定任务更好些。

您好，想请教一下，net_utils.py中是不是只有CroMB没有ConMB，ConMB是不是需要根据论文里的公式自己写。

**Comment by zifuwan** [comment]
Hi, the code of ConMB can be found here: https://github.com/zifuwan/Sigma/blob/main/models/encoders/dual_vmamba.py#L53

**Comment by SuGuilin** [comment]
> 请问fusion module可以即插即用吗～ 我试了一下效果变差了，不知道是哪里出了问题，我融合的是两种医学MRI图像Flair和T1。 融合之前我也对两个特征进行了contiguous和FRM处理。

请问您是如何操作的，我现在也想融合，但不知道是我不是修改的问题，导致融合后的图没办法看

**Comment by ParkMinyoung0304** [comment]
> > 请问fusion module可以即插即用吗～ 我试了一下效果变差了，不知道是哪里出了问题，我融合的是两种医学MRI图像Flair和T1。 融合之前我也对两个特征进行了contiguous和FRM处理。
> 
> 请问您是如何操作的，我现在也想融合，但不知道是我不是修改的问题，导致融合后的图没办法看

我试了下可以即插即用的融合，也就是直接换不同种类的图片，但是想请问您是如何可视化融合后的图片的，我只找到了visualize.py的代码，但不知道如何可视化
