### ISSUE TITLE
exchange of parameters C

### ISSUE THREAD

**Issue by JHChen1** [zifuwan/Sigma#14]
Does the exchange of parameters C require that the L of the two modes be equal? ​​For example, sequences BL1D and BL2D cannot be exchanged?

**Comment by zifuwan** [comment]
Hi, the input shapes are expected to be the same. For different input shapes, you can either use a linear layer before sending to SSMs, or change the linear layer [here](https://github.com/zifuwan/Sigma/blob/main/models/encoders/vmamba.py#L1589).
