### ISSUE TITLE
pretrained VMamba weights cannot be downloaded

### ISSUE THREAD

**Issue by YiangAhead** [zifuwan/Sigma#17]

**Comment by YiangAhead** [comment]
The download link doesn't work.

**Comment by zifuwan** [comment]
Hi, I've uploaded the weight [here](https://github.com/zifuwan/Sigma/tree/main/pretrained/vmamba)

**Comment by YiangAhead** [comment]
Thanks!
&nbsp;


1325473360
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Zifu ***@***.***&gt;; 
发送时间: 2024年6月18日(星期二) 晚上7:51
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [zifuwan/Sigma] pretrained VMamba weights cannot be downloaded (Issue #17)














 
Hi, I've uploaded the weight here
