### ISSUE TITLE
pretrained weights

### ISSUE THREAD

**Issue by Jia-hao999** [zifuwan/Sigma#19]
I want to train Sigma on my device. But I can not find suitable vmamba pretrained weights in the provided link. Can you provide ''vssmsmall_dp03_ckpt_epoch_238.pth'' and ''vssmbase_dp06_ckpt_epoch_241.pth'' for me. Thanks!

**Comment by zifuwan** [comment]
Hi, have you tried to download the weights [here](https://github.com/zifuwan/Sigma/blob/main/pretrained/vmamba/vssmsmall_dp03_ckpt_epoch_238.pth) by clicking at the download button?

**Comment by Jia-hao999** [comment]
Oh! I didn't notice there was a link. Thanks！
