### ISSUE TITLE
关于CroMB的一些问题

### ISSUE THREAD

**Issue by chenzean** [zifuwan/Sigma#20]
作者，你好，
   我看论文中您写道：为了实现这一点，我们建议在选择性扫描操作中使用互补模态生成的C矩阵，这使得SSM能够从另一个模态引导的隐藏状态中重建输出。
   我想知道为啥你只选择使用互补模态生成的C矩阵而不是互补模态生成的B，C矩阵或者是互补模态生成的A，B，C矩阵？
   这一点我不太理解。

**Comment by zifuwan** [comment]
Thanks for the question. We use matrix B for the hidden state according to the original theory of SSM, as indicated by Eq. 1. In CroMB, we use matrix C to reconstruct output from the hidden state. We conduct experiments to explore the benefit of using matrix B and B/C for CroMB as the table below. It can be seen that using matrix C in CroMB reaches the optimal performance.
<img width="589" alt="image" src="https://github.com/zifuwan/Sigma/assets/77483744/33b3d3e3-e1e6-4389-8a64-8638ec764f6c">
