### ISSUE TITLE
Two Questions About CroMB

### ISSUE THREAD

**Issue by ZHUXIUJINChris** [zifuwan/Sigma#21]
Thank you for the excellent work! 

1. Why did you swap the C matrix? Have you tried swapping the B matrix?
2. Other Mamba fusion models usually adopt a gating mechanism. Compared to them, what are the advantages of this model?

**Comment by zifuwan** [comment]
Hi, thanks for your interest.

1. Please refer to this [response](https://github.com/zifuwan/Sigma/issues/20) for the explanation.
2. It would be great if you could elaborate on the gating mechanism you refer to. I'm not sure if the `scale` operation in ConMB is similar to the gating mechanism.

**Comment by ZHUXIUJINChris** [comment]
Thank you for your response. 

1. I noticed that the results for swapping the C matrix are the best. Do you know the specific reason for this?
2. In models such as "Pan-Mamba," "Fusion mamba," "MambaDFuse," and "SurvMamba," an activation function is typically used to control the two pathways, achieving the effect of transmitting useful information and filtering out useless information.

Pan-Mamba:
https://arxiv.org/pdf/2402.12192
![image](https://github.com/zifuwan/Sigma/assets/154212310/23b14979-92fb-4cc4-bb7c-65aac7d4e69f)
Fusion Mamba:
https://arxiv.org/pdf/2404.09146
![def15f23c1c1d2bc73be44f763950f7](https://github.com/zifuwan/Sigma/assets/154212310/535137f7-2afc-4c34-bdb3-428d38be45fc)
MambaDfuse:
https://arxiv.org/pdf/2404.08406
![1719976263981](https://github.com/zifuwan/Sigma/assets/154212310/669f17f6-f8b4-429c-989e-8ce2d660332e)
SurvMamba:
https://arxiv.org/pdf/2404.08027
![image](https://github.com/zifuwan/Sigma/assets/154212310/d1e27211-8f80-4b40-affa-2ac18f9b9d36)

**Comment by zifuwan** [comment]
Sorry for the late response.
1. We suppose Matrix C is used to decode the information from the hidden state and can guide the reconstruction of the complementary modality. However, it is always recommended to experiment for the optimal parameter selection.
2. Activation function can indeed be useful. However, in our method, we focus on a simple implementation to explore the potential of Mamba in multimodal learning.
Hope this helps.
