### ISSUE TITLE
weight is over its data quota

### ISSUE THREAD

**Issue by TZW-056** [zifuwan/Sigma#22]
Hi 👋 ! Thanks for your wonderful work!  But when I clone this repo, weight of vmamba can not be download successfully due to repository's data quota. Just like below:
![image](https://github.com/user-attachments/assets/37963327-b687-480d-9629-a6f5c8788425)
  I tried to use vmamba weight in the original repo. But the performance is not good, just only 48% (mIoU) in MFDataset. So I consider the vmamba weight in your repo is much better than [MzeroMiko](https://github.com/MzeroMiko). 
  I would appreciate it if you could give me the weight in other way (Google Driver or others is OK!) to  help me graduate 🌹 ！

**Comment by zifuwan** [comment]
Hi, I've uploaded the checkpoints here: https://drive.google.com/drive/folders/1kfp3aXku-A9ZZfbFLi8DfYTBYrj7uiz1?usp=drive_link
Sorry for the inconvinience.

**Comment by TZW-056** [comment]
Thanks for your kindly providing！
