### ISSUE TITLE
NYU Dataset with 4 channel depth images.

### ISSUE THREAD

**Issue by yuwenmichael** [zifuwan/Sigma#23]
Hi, 

I downloaded your preprocessed dataset from google drive and found that the depth image is of 4 channels? May I know what exact channel(s) you pass to the model for training and testing?

Also I noted that in the config file https://github.com/zifuwan/Sigma/blob/fcacbd92d0f2c3f8c09d79c1e12631d577134a30/configs/config_nyu.py#L32, the model takes only one channel for training if it is correct, I was wondering which channel you referring to?

Thanks,

**Comment by zifuwan** [comment]
Hi, we read the depth image with grey mode (1 channel) and copy it to 3 channels before passing to the model.
Please refer to this code: [link](https://github.com/zifuwan/Sigma/blob/main/dataloader/RGBXDataset.py#L51)
Hope this can be useful.
