### ISSUE TITLE
I want to ask questions about some parameters in config_MFNet.py

### ISSUE THREAD

**Issue by HarisIqbal89** [zifuwan/Sigma#24]
I want to know the mean of C.checkpoint_start_epoch and C.checkpoint_step
thank you for your response  :)

**Comment by HarisIqbal89** [comment]
实际上我想要将代码调整为：每训练一个epoch就对比最好的mIoU，想问问作者，我只需要调整这两个参数就可以了吗？谢谢您了

**Comment by HarisIqbal89** [comment]
我有点奇怪，为什么当epoch >= config.checkpoint_start_epoch时，代码会将epoch重新从1开始计数再到config.checkpoint_start_epoch循环...

**Comment by zifuwan** [comment]
Hi, thanks for the question. Yes, to evaluate the model for every epoch, you only need to change the two parameters, e.g., ```
C.checkpoint_start_epoch = 0
C.checkpoint_step = 1
```
For the second question, sorry I didn't notice an issue like that, could you take a screenshot and I will also try to reproduce myself.
