### ISSUE TITLE
Error when eval during training

### ISSUE THREAD

**Issue by yuwenmichael** [zifuwan/Sigma#25]
I encoutered an error when running the code in distributed training mode in the following code:
https://github.com/zifuwan/Sigma/blob/fcacbd92d0f2c3f8c09d79c1e12631d577134a30/engine/evaluator.py#L496

The error message is:
RuntimeError: permute(sparse_coo): number of dimensions in the tensor input does not match the length of the desired ordering of dimensions i.e. input.dim() = 4 is not equal to len(dims) = 3

When I print the shape of the "score" tensor I got torch.Size([1, 0, 320, 640]) where the second dimension is of zero size. May I know what is the expected behaviour of the "score" tensor? Is there a bug in the code?

Thanks for helping out.

**Comment by zifuwan** [comment]
Hi, I haven't encountered this issue before. I recommend print out the inputs of `scale_process_rgbX` to check if they are right.
