### ISSUE TITLE
error when downloading the pretrained VMamba weights

### ISSUE THREAD

**Issue by awei0116** [zifuwan/Sigma#26]
Hello auther: When I downloaded the pretrained VMamba weights by git clone, it occured that "Downloading pretrained/vmamba/vssmbase_dp06_ckpt_epoch_241.pth (305 MB)
Error downloading object: pretrained/vmamba/vssmbase_dp06_ckpt_epoch_241.pth (870b84f): Smudge error: Error downloading pretrained/vmamba/vssmbase_dp06_ckpt_epoch_241.pth (870b84f4f988a46cac96614677c898dbf888f68ec82e5297a623b7fe166ea018): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access."

Then I used "git lfs fetch --all" again ,I met de same error.

The error means maybe you should check you git's data quota. Hope you address this issue at your convenience！Thanks!

**Comment by zifuwan** [comment]
Hi, I've uploaded the checkpoints here: https://drive.google.com/drive/folders/1kfp3aXku-A9ZZfbFLi8DfYTBYrj7uiz1?usp=drive_link
Sorry for the inconvinience.
