### ISSUE TITLE
Question about the calculation of FLOPs

### ISSUE THREAD

**Issue by ruisong8** [zifuwan/Sigma#27]
Hi. Thanks for your great work. 
I tried to use some open source method to calculate the FLOPs of Sigma-T, like THOP and ptflops. They both show a result around 75.26 GMac. I noticed there is some discussion about how to calculate Mamba's FLOPs and maybe these old methods is not accurate enough when it comes to Mamba. So I want to know how the FLOPs in the Paper is calculate? Thanks.

**Comment by zifuwan** [comment]
Hi, we tried the calculation code of VMamba from [here](https://github.com/MzeroMiko/VMamba/blob/7c79eb8928abb5c7ee4063d493ef91ba681ec7ac/analyze/flops.py). However, no difference was found with the calculation [here](https://github.com/zifuwan/Sigma/blob/main/utils/calculate_params.py).

**Comment by ruisong8** [comment]
I see. Thank you very much.
