### ISSUE TITLE
ModuleNotFoundError: No module named 'selective_scan_cuda_core

### ISSUE THREAD

**Issue by 1774537072** [zifuwan/Sigma#3]
"ModuleNotFoundError: No module named 'selective_scan_cuda_core"
how to solve this problem ?

**Comment by zifuwan** [comment]
Hi, have you tried to install Mamba by: `cd models/encoders/selective_scan && pip install . && cd ../../..`? You can check your installation by running:
```
from selective_scan import selective_scan_fn
import selective_scan_cuda_core as selective_scan_cuda
```
If no error is observed, it means your installation is successful.

**Comment by 1774537072** [comment]
![2G4 98VX}(`}RAI@V%E4ELQ](https://github.com/zifuwan/Sigma/assets/82571029/e7c1a6dd-a90f-4a5e-87c0-9ee4719d4dbe)
Thank you very much for your answer. i can only import "selective_scan_cuda" but cant import selective ,why?

**Comment by zifuwan** [comment]
Hi, have you tried to install a new environment for Sigma following README? I've not encountered this issue, probably you can go to VMamba issue for some help: [https://github.com/MzeroMiko/VMamba/issues/76](VMamba).

**Comment by zoujing925** [comment]
Hi, @1774537072  did you solve the problem? I encountered the same problem.

I installed a new environment for Sigma following README, but i stall encounter this problem

**Comment by 1774537072** [comment]
I solved the problem, it should have been a cuda version mismatch，i use cuda 11.7.0 and install the selective_can and successful.
i think you need check u cuda and just install the package"selective_scan" which author provides
do not install mamba_ssm, This is different from what the author offers

**Comment by zoujing925** [comment]
Get it. Thanks a lot!
