### ISSUE TITLE
A question about the ConMamba module

### ISSUE THREAD

**Issue by Assioncreed** [zifuwan/Sigma#30]
Thank you for your excellent work.
I found two scan features in the ConMamba module that need to be multiplied with another scaling parameter.
What I would like to know is what the scaling parameter does and why it should be multiplied with the scaling parameter derived from one scan feature and not with the scaling parameter derived from itself?
The code is as follows：

 y_rgb = y_rgb * x_e_exitation
 y_e = y_e * x_rgb_exitation

**Comment by zifuwan** [comment]
Hi, thanks for the great question. This scaling parameter can be considered as an excitation factor that decides which part of the features should be activated. Intuitively, we want to enhance cross-modal communication (similar to cross-attention), resulting in the multiplication with one another. Actually, we have also conducted experiments that use the scaling parameter from itself and found no significant difference.
