### ISSUE TITLE
Question about cross-scan in CroMB

### ISSUE THREAD

**Issue by ruisong8** [zifuwan/Sigma#31]
Hi, thanks for your work.

When I read the code, I noticed that in CroMB, it looks like the block did not really use cross-scan module. Instead, it uses einops.rearrange to expand the two-dimensional image into one-dimensional vector. That means it only have one scanning strategy instead of four as in VMamba and your backbone. I would like to know what the considerations are for doing this. Is it to make the code implementation simpler, or is it due to the consideration of parameter num and Flops? Or have you done experiments to verify that the effects of scanning in one direction and scanning in four directions in CroMB are similar?
Thanks a lot.
![1727415635016](https://github.com/user-attachments/assets/43967f5e-f3d4-419e-bb5a-307874ed13aa)

**Comment by zifuwan** [comment]
Hi, Mamba is a sequential modeling method, hence expanding to one dimension to perform SSM is the same as applying SSM four times. I couldn't clearly remember whether this implementation reduced CUDA memory, but the performance was similar(expand to 1d and SSM **v.s.** apply SSM 4 times).
