### ISSUE TITLE
problem about train

### ISSUE THREAD

**Issue by zhouyancheng99** [zifuwan/Sigma#33]
Why do you get checkpoints and stop training after 50 rounds?
![Uploading checkpoint.png…]()

**Comment by zhouyancheng99** [comment]
![checkpoint](https://github.com/user-attachments/assets/1cd80389-cd18-45c1-afca-1b115ed3ab1a)

**Comment by ParkMinyoung0304** [comment]
i also encounter same problem,can you share solution ?
