### ISSUE TITLE
Weights and demo hosting

### ISSUE THREAD

**Issue by merveenoyan** [zifuwan/Sigma#8]
Hello 🙋‍♀️ congratulations on the release!
It would be great if the model and the demos would be hosted on Hugging Face for people to try. We can also help you out with hardware to host your demo. It would make the model more discoverable and improve the visibility. 
What do you think?

**Comment by zifuwan** [comment]
Hi, thank you so much for reaching out. It would be great if we could host our demo on Hugging Face for more people to try. Can we talk about this in more detail through email: zifuw@andrew.cmu.edu? Thanks.
