### ISSUE TITLE
How to generate a detection result figure like Figure 5 in the paper?

### ISSUE THREAD

**Issue by cpy0029** [zifuwan/Sigma#9]
How to generate a detection result figure like Figure 5 in the paper?
Thanks!!!

**Comment by zifuwan** [comment]
Hi, for visualization, you can use the commend `CUDA_VISIBLE_DEVICES="0,1,2,3,4,5,6,7" python eval.py -d="0" -n "dataset_name" -e="epoch_number" -p="visualize_savedir"`. The visualization result will be saved in the path specified by `-p="visualize_savedir"`.
